service: appsync-simulator-error-repro

plugins:
  - serverless-appsync-plugin
  - serverless-appsync-simulator
  - serverless-offline

custom:
  appSync:
    schema: schema.graphql
    name: ${self:service}-${self:provider.stage}
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      defaultAction: ALLOW
      userPoolId:
        Ref: CognitoUserPool
    mappingTemplates:
      - dataSource: SomeLambdaDataSource
        type: Query
        field: something
    dataSources:
      - type: AWS_LAMBDA
        name: SomeLambdaDataSource
        description: "Some Data Source"
        config:
          functionName: someLambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  memorySize: 1024
  timeout: 600

functions:
  someLambda:
    handler: some-lambda.handler

resources:
  # - ${file(s3-bucket.yml)}
  - ${file(cloud-front.yml)}
